### ISSUE TITLE
I'd like to be able to define a folder to output the files to.

### ISSUE THREAD

**Issue by DeliaCodes** [abandisch/download-podcasts#1]
Currently the App only outputs to the folder that the app is run in. I'd like to be able to change that and specify a folder / create a folder to download the files to.

**Comment by abandisch** [comment]
- [x] Automatically create downloads folder if it doesn't exist
- [x] Create podcast title subdirectory under downloads folder to store mp3's
- [x] Store the mp3's in the newly created podcast folder
